version: '3.7'

services:
  event_platform:
    container_name: event_platform
    image: "lensesio/fast-data-dev"
    network_mode: "host"
    ports:
      - "9092:9092"
      - "8084:8084"
      - "8082:8082"
      - "8083:8083"
      - "2181:2181"
      - "3030:3030"
      - "9001:9001"
      - "8081:8081"
    environment:
      - "SAMPLEDATA=0"
      - "RUNNING_SAMPLEDATA=0"
      - "RUNTESTS=0"
      - "DISABLE_JMX=1"
      - "SUPERVISORWEB=1"
      - "ADV_HOST=127.0.0.1"
      - "KAFKA_REST_SCHEMA_REGISTRY_URL=http://localhost:8084"
      - "lenses.schema.registry.urls.url=http://localhost:8084"
      - "lenses.schema.registry.topics=_schemas"
      - "lenses.schema.registry.delete=true"
      - "lenses.schema.registry.auth=NONE"
  player_one_auto:
    container_name: game_find_three_player_one
    restart: always
    image: lilianferesl/gamefindthree:player-one-auto-latest
    network_mode: "host"
    ports:
      - 8089:8089
    environment:
      - "APP_PORT=8089"
      - "START_MODE=auto"
      - "APP_PLAYER=player1"
      - "GROUP_ID=game-find-three-player-p1"
  player_one_manual:
    container_name: game_find_three_player_one
    restart: always
    image: lilianferesl/gamefindthree:player-one-manual-latest
    depends_on:
      - event_platform
    command: event_platform:8081
    ports:
      - 8089:8089
    network_mode: "host"
    environment:
      - "APP_PORT=8089"
      - "START_MODE=manual"
      - "APP_PLAYER=player1"
      - "GROUP_ID=game-find-three-player-p1"
  player_two_manual:
    container_name: game_find_three_player_two
    restart: always
    image: lilianferesl/gamefindthree:player-two-manual-latest
    network_mode: "host"
    ports:
      - 8085:8085
    environment:
      - "APP_PORT=8085"
      - "START_MODE=manual"
      - "APP_PLAYER=player2"
      - "GROUP_ID=game-find-three-player-p2"